import { IsString, IsNotEmpty, IsIn, MaxLength } from 'class-validator';

/**
 * DTO for registering a biometric credential on a device.
 * The userId is extracted from the JWT token, not from the request body.
 */
export class RegisterBiometricDto {
  /** User who owns this credential (populated from JWT, not body) */
  readonly userId!: string;

  /** Device identifier */
  @IsString()
  @IsNotEmpty()
  @MaxLength(255)
  readonly deviceId!: string;

  /** Public key generated by the device's Secure Enclave / Keystore */
  @IsString()
  @IsNotEmpty()
  @MaxLength(4096)
  readonly publicKey!: string;

  /** Type of biometric: 'fingerprint' | 'face_id' */
  @IsString()
  @IsNotEmpty()
  @IsIn(['fingerprint', 'face_id'])
  readonly credentialType!: 'fingerprint' | 'face_id';
}
