/**
 * Report & runbook renderer.
 *
 * Renders the CANONICAL inventory model into presentation artifacts:
 *   - the human doc (`docs/CONFIGURATION-INVENTORY.md`, placeholders only) with
 *     per-surface views,
 *   - the reconciled `.env.example` shape,
 *   - a machine-readable findings JSON.
 *
 * This projection is ONE-DIRECTIONAL: it reads the canonical model and writes
 * presentation artifacts, and never treats those artifacts as an authority
 * feeding existence/classification/requiredness back into the catalog.
 */

import type {
  ConfigVariable,
  Finding,
  InventoryReport,
  Surface,
} from './inventory.model';

/** Assemble the aggregate report; `compliant` is false iff a blocking finding exists. */
export function buildInventoryReport(
  variables: readonly ConfigVariable[],
  findings: readonly Finding[],
): InventoryReport {
  const compliant = !findings.some((finding) => finding.blocking);
  return { variables, findings, compliant };
}

const SURFACE_ORDER: readonly Surface[] = ['API', 'AI', 'MOBILE', 'INFRA'];

/**
 * Render the human-facing inventory Markdown doc from the canonical model.
 * Placeholders only — never a real value.
 */
export function renderInventoryDoc(report: InventoryReport): string {
  const lines: string[] = [];
  lines.push('# Configuration Inventory');
  lines.push('');
  lines.push(
    '> Generated by `tools/config-inventory`. Placeholders only — real values live in',
  );
  lines.push('> the runtime environment (`.env`, VPS env, Vault) and are NEVER committed.');
  lines.push('> This document is a projection of the canonical inventory model.');
  lines.push('');
  lines.push(`**Compliant:** ${report.compliant ? 'yes' : 'NO (blocking findings present)'}`);
  lines.push('');

  for (const surface of SURFACE_ORDER) {
    const forSurface = report.variables.filter((variable) => variable.surface === surface);
    if (forSurface.length === 0) {
      continue;
    }
    lines.push(`## ${surface} surface`);
    lines.push('');
    lines.push(renderVariableTable(forSurface));
    lines.push('');
  }

  lines.push(renderFindingsSection(report.findings));
  lines.push('');
  lines.push(renderRunbookSection());
  lines.push('');
  return lines.join('\n');
}

/** Render the per-surface variable table (orthogonal scope/env columns). */
function renderVariableTable(variables: readonly ConfigVariable[]): string {
  const header =
    '| name | group | kind | requiredScope | env applicability | placeholder | consumed_by | source_type |';
  const divider = '| --- | --- | --- | --- | --- | --- | --- | --- |';
  const rows = variables.map((variable) => {
    const sourceTypes = [...new Set(variable.provenance.map((p) => p.sourceType))].join(', ');
    const consumers = variable.consumedBy.join('<br/>');
    return (
      `| ${variable.name} | ${variable.group} | ${variable.kind} | ` +
      `${variable.requiredScope.join(', ')} | ${variable.envApplicability.join(', ')} | ` +
      `${variable.placeholder} | ${consumers} | ${sourceTypes} |`
    );
  });
  return [header, divider, ...rows].join('\n');
}

/** Render the findings section (empty findings become an explicit "none"). */
function renderFindingsSection(findings: readonly Finding[]): string {
  const lines: string[] = ['## Findings', ''];
  if (findings.length === 0) {
    lines.push('No findings. No known secret-pattern exposure detected.');
    return lines.join('\n');
  }
  lines.push('| code | variable | blocking | detail |');
  lines.push('| --- | --- | --- | --- |');
  for (const finding of findings) {
    lines.push(
      `| ${finding.code} | ${finding.variable ?? ''} | ${finding.blocking} | ${finding.detail} |`,
    );
  }
  return lines.join('\n');
}

/** Render the deterministic bring-up runbook (no rotation). */
function renderRunbookSection(): string {
  return [
    '## Bring-up runbook (no rotation)',
    '',
    '1. Copy `.env.example` to `.env` (per surface: API, AI, mobile, infra).',
    '2. Fill operator-supplied values into the runtime env (never `.env.example`).',
    '3. `docker compose up` the infra services.',
    '4. Start each service so its `validateXxxConfig()` runs (fail-fast).',
    '5. Adapt runtime env variables until every validator passes.',
    '6. Result: **configured & startup-valid** (NOT operational/healthy — that is `full-audit`).',
    '',
    'This tool never rotates, revokes, moves, or stages any credential. A discovered',
    'real secret in a tracked artifact is a blocking `SECRET_EXPOSURE` finding: reported,',
    'config NOT marked compliant, secret left untouched.',
  ].join('\n');
}

/**
 * Render the reconciled `.env.example` shape from the canonical model, grouped
 * by surface then group, with a safe placeholder and required/optional comment.
 */
export function renderReconciledEnvExample(variables: readonly ConfigVariable[]): string {
  const lines: string[] = [];
  lines.push('# ==============================================================================');
  lines.push('# BidClean — Environment Variables (reconciled by tools/config-inventory)');
  lines.push('# Copy this file to .env and fill in your values.');
  lines.push('# NEVER commit .env to git (it is in .gitignore). Placeholders only below.');
  lines.push('# ==============================================================================');
  lines.push('');

  for (const surface of SURFACE_ORDER) {
    const forSurface = variables.filter((variable) => variable.surface === surface);
    if (forSurface.length === 0) {
      continue;
    }
    for (const group of distinctGroups(forSurface)) {
      lines.push(`# --- ${surface}: ${group} ---`);
      for (const variable of forSurface.filter((item) => item.group === group)) {
        const required = variable.requiredScope.includes('runtime') ? 'required' : 'optional';
        lines.push(`# ${variable.kind} · ${required} · consumed by ${variable.consumedBy[0] ?? '—'}`);
        lines.push(`${variable.name}=${variable.placeholder}`);
      }
      lines.push('');
    }
  }
  return lines.join('\n');
}

/** Distinct group names in first-seen order for a surface's variables. */
function distinctGroups(variables: readonly ConfigVariable[]): string[] {
  const groups: string[] = [];
  for (const variable of variables) {
    if (!groups.includes(variable.group)) {
      groups.push(variable.group);
    }
  }
  return groups;
}

/** Serialize the findings to a stable, CI-consumable JSON string. */
export function renderFindingsJson(report: InventoryReport): string {
  return JSON.stringify(
    {
      compliant: report.compliant,
      findingCount: report.findings.length,
      blockingCount: report.findings.filter((finding) => finding.blocking).length,
      findings: report.findings,
    },
    null,
    2,
  );
}

/** Serialize the canonical variable catalog to a stable, machine-readable JSON string. */
export function renderCatalogJson(variables: readonly ConfigVariable[]): string {
  return JSON.stringify(
    {
      variableCount: variables.length,
      variables,
    },
    null,
    2,
  );
}
