import { Injectable, Logger, HttpException, HttpStatus, UnauthorizedException, GoneException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, IsNull } from 'typeorm';
import * as crypto from 'crypto';
import { BiometricCredential } from '../entities/biometric-credential.entity';
import { BiometricChallenge as BiometricChallengeEntity } from '../entities/biometric-challenge.entity';
import { User } from '../entities/user.entity';
import { KeycloakService } from '../keycloak/keycloak.service';
import { BiometricVerifyDto } from '../dto/biometric-verify.dto';
import { AuthTokens, BiometricChallenge } from '../auth.types';

const NONCE_SIZE_BYTES = 32;
const CHALLENGE_EXPIRY_MS = 30_000;

export interface RegisterCredentialOptions {
  readonly userId: string;
  readonly deviceId: string;
  readonly publicKey: string;
  readonly credentialType: string;
}

/**
 * Biometric authentication service.
 *
 * Manages device credentials, challenge generation,
 * and signature verification for passwordless login.
 * Biometric data never leaves the device — only the
 * public key is stored server-side.
 */
@Injectable()
export class BiometricService {
  private readonly logger = new Logger(BiometricService.name);

  constructor(
    @InjectRepository(BiometricCredential)
    private readonly credentialRepository: Repository<BiometricCredential>,
    @InjectRepository(BiometricChallengeEntity)
    private readonly challengeRepository: Repository<BiometricChallengeEntity>,
    @InjectRepository(User)
    private readonly userRepository: Repository<User>,
    private readonly keycloakService: KeycloakService,
  ) {}

  /**
   * Store a device's public key for biometric authentication.
   * The key is generated by the device's Secure Enclave / Keystore.
   *
   * - If no credential exists for (userId, deviceId), creates one.
   * - If one exists and is active (not revoked), updates publicKey and credentialType.
   * - If one exists and is revoked, revokes the old record and creates a new one.
   */
  async registerCredential(options: RegisterCredentialOptions): Promise<void> {
    const { userId, deviceId, publicKey, credentialType } = options;

    const existing = await this.credentialRepository.findOne({
      where: { userId, deviceId },
    });

    if (!existing) {
      await this.createCredential(userId, deviceId, publicKey, credentialType);
      this.logger.log(`Biometric credential registered for user ${userId} on device ${deviceId}`);
      return;
    }

    if (!existing.revokedAt) {
      // Active credential — update public key (re-enrollment)
      existing.publicKey = publicKey;
      existing.credentialType = credentialType;
      await this.credentialRepository.save(existing);
      this.logger.log(`Biometric credential updated for user ${userId} on device ${deviceId}`);
      return;
    }

    // Revoked credential — create a new one
    // The unique constraint is on (userId, deviceId), so remove the old record first
    await this.credentialRepository.remove(existing);
    await this.createCredential(userId, deviceId, publicKey, credentialType);
    this.logger.log(`Biometric credential re-registered (previous was revoked) for user ${userId} on device ${deviceId}`);
  }

  private async createCredential(
    userId: string,
    deviceId: string,
    publicKey: string,
    credentialType: string,
  ): Promise<BiometricCredential> {
    const credential = this.credentialRepository.create({
      userId,
      deviceId,
      publicKey,
      credentialType,
    });

    return this.credentialRepository.save(credential);
  }

  /**
   * Generate a 32-byte nonce for biometric challenge.
   * Challenge is device-bound and expires after 30 seconds.
   */
  async generateChallenge(deviceId: string): Promise<BiometricChallenge> {
    const nonce = crypto.randomBytes(NONCE_SIZE_BYTES).toString('base64url');
    const expiresAt = new Date(Date.now() + CHALLENGE_EXPIRY_MS);

    const challenge = this.challengeRepository.create({
      deviceId,
      nonce,
      expiresAt,
      used: false,
    });

    await this.challengeRepository.save(challenge);

    this.logger.log(`Biometric challenge generated for device ${deviceId}`);

    return { challenge: nonce, expiresAt: expiresAt.toISOString() };
  }

  /**
   * Validate a signed biometric challenge and return tokens.
   * Verifies the signature against the stored public key,
   * ensures challenge is not expired or reused.
   */
  async verifyChallenge(dto: BiometricVerifyDto): Promise<AuthTokens> {
    const { deviceId, challenge: nonce, signature } = dto;

    const challengeEntity = await this.findAndValidateChallenge(nonce, deviceId);
    await this.markChallengeAsUsed(challengeEntity);

    const credential = await this.findActiveCredential(deviceId);
    this.verifySignature(nonce, signature, credential.publicKey, credential.credentialType);

    const user = await this.findUserForCredential(credential.userId);
    const tokens = await this.exchangeTokensForUser(user.keycloakId);

    await this.updateLastUsed(credential);

    this.logger.log(`Biometric verification successful for user ${user.id} on device ${deviceId}`);
    return tokens;
  }

  // -------------------------------------------------------------------------
  // Private verification helpers
  // -------------------------------------------------------------------------

  private async findAndValidateChallenge(
    nonce: string,
    deviceId: string,
  ): Promise<BiometricChallengeEntity> {
    const challenge = await this.challengeRepository.findOne({
      where: { nonce, deviceId },
    });

    if (!challenge) {
      throw new GoneException('Challenge expired or not found, request a new one');
    }

    if (challenge.used) {
      throw new GoneException('Challenge already used, request a new one');
    }

    if (challenge.expiresAt < new Date()) {
      throw new GoneException('Challenge expired, request a new one');
    }

    return challenge;
  }

  private async markChallengeAsUsed(challenge: BiometricChallengeEntity): Promise<void> {
    challenge.used = true;
    await this.challengeRepository.save(challenge);
  }

  private async findActiveCredential(deviceId: string): Promise<BiometricCredential> {
    const credential = await this.credentialRepository.findOne({
      where: { deviceId, revokedAt: IsNull() },
    });

    if (!credential) {
      throw new UnauthorizedException('No active biometric credential for this device');
    }

    return credential;
  }

  private verifySignature(
    nonce: string,
    signature: string,
    publicKey: string,
    credentialType: string,
  ): void {
    const isValid = this.cryptoVerify(nonce, signature, publicKey, credentialType);

    if (!isValid) {
      throw new UnauthorizedException('Signature verification failed');
    }
  }

  private cryptoVerify(
    nonce: string,
    signature: string,
    publicKey: string,
    credentialType: string,
  ): boolean {
    try {
      const signatureBuffer = Buffer.from(signature, 'base64');
      const algorithm = this.getAlgorithm(credentialType);

      return crypto.verify(
        algorithm,
        Buffer.from(nonce),
        publicKey,
        signatureBuffer,
      );
    } catch (error) {
      this.logger.warn(`Signature verification error: ${error}`);
      return false;
    }
  }

  private getAlgorithm(credentialType: string): string {
    switch (credentialType.toLowerCase()) {
      case 'ec':
      case 'ecdsa':
      case 'es256':
        return 'SHA256';
      case 'rsa':
      case 'rs256':
        return 'SHA256';
      default:
        return 'SHA256';
    }
  }

  private async findUserForCredential(userId: string): Promise<User> {
    const user = await this.userRepository.findOne({ where: { id: userId } });

    if (!user) {
      throw new UnauthorizedException('User associated with credential not found');
    }

    return user;
  }

  private async exchangeTokensForUser(keycloakId: string): Promise<AuthTokens> {
    try {
      return await this.keycloakService.getTokensForUser(keycloakId);
    } catch (error) {
      this.logger.error(`Token exchange failed for keycloakId ${keycloakId}: ${error}`);
      throw new HttpException(
        'Failed to establish session with identity provider',
        HttpStatus.BAD_GATEWAY,
      );
    }
  }

  private async updateLastUsed(credential: BiometricCredential): Promise<void> {
    credential.lastUsedAt = new Date();
    await this.credentialRepository.save(credential);
  }
}
